# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0012_userrole_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubgrade',
            options={'ordering': ['club', 'grade']},
        ),
        migrations.AlterField(
            model_name='race',
            name='club',
            field=models.ForeignKey(help_text=b' ', on_delete=django.db.models.deletion.CASCADE, related_name='races', to='site.Club'),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(help_text=b' '),
        ),
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, default=b'', help_text=b' '),
        ),
        migrations.AlterField(
            model_name='race',
            name='location',
            field=models.ForeignKey(help_text=b' ', on_delete=django.db.models.deletion.CASCADE, to='site.RaceCourse'),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published'), (b'w', b'Withdrawn')], default=b'd', help_text=b' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='race',
            name='time',
            field=models.TimeField(help_text=b'eg. 08:00, 18:30'),
        ),
        migrations.AlterField(
            model_name='race',
            name='title',
            field=models.CharField(help_text=b'Enter a title for the race', max_length=100),
        ),
        migrations.AlterField(
            model_name='race',
            name='website',
            field=models.URLField(blank=True, help_text=b' ', max_length=400),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='grade',
            field=models.CharField(max_length=10, verbose_name=b'Grade'),
        ),
        migrations.AlterUniqueTogether(
            name='clubgrade',
            unique_together=set([('club', 'grade', 'rider')]),
        ),
    ]
