# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0013_auto_20160206_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubgrade',
            options={'ordering': ['rider', 'grade']},
        ),
        migrations.AlterUniqueTogether(
            name='clubgrade',
            unique_together=set([]),
        ),
    ]
