# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0015_auto_20160307_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Bib Number'),
        ),
    ]
