# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 02:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djangoyearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0016_auto_20160307_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', djangoyearlessdate.models.YearField(blank=True, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site.Club')),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='dob',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name=b'Date of Birth'),
        ),
        migrations.AddField(
            model_name='rider',
            name='emergencyname',
            field=models.CharField(default=b'', max_length=100, verbose_name=b'Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='rider',
            name='emergencyphone',
            field=models.CharField(default=b'', max_length=20, verbose_name=b'Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='rider',
            name='emergencyrelationship',
            field=models.CharField(default=b'', max_length=20, verbose_name=b'Emergency Contact Relationship'),
        ),
        migrations.AddField(
            model_name='rider',
            name='phone',
            field=models.CharField(default=b'', max_length=20, verbose_name=b'Phone'),
        ),
        migrations.AddField(
            model_name='rider',
            name='postcode',
            field=models.CharField(default=b'', max_length=4, verbose_name=b'Postcode'),
        ),
        migrations.AddField(
            model_name='rider',
            name='state',
            field=models.CharField(choices=[(b'ACT', b'Australian Capital Territory'), (b'NSW', b'New South Wales'), (b'NT', b'Northern Territory'), (b'QLD', b'Queensland'), (b'SA', b'South Australia'), (b'TAS', b'Tasmania'), (b'VIC', b'Victoria'), (b'WA', b'Western Australia')], default=b'NSW', max_length=10, verbose_name=b'State'),
        ),
        migrations.AddField(
            model_name='rider',
            name='streetaddress',
            field=models.CharField(default=b'', max_length=100, verbose_name=b'Address'),
        ),
        migrations.AddField(
            model_name='rider',
            name='suburb',
            field=models.CharField(default=b'', max_length=100, verbose_name=b'Suburb'),
        ),
        migrations.AddField(
            model_name='membership',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.Rider'),
        ),
    ]
