# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0017_auto_20160327_0512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['date', 'signontime']},
        ),
        migrations.RenameField(
            model_name='race',
            old_name='time',
            new_name='signontime'
        ),
        migrations.AddField(
            model_name='race',
            name='starttime',
            field=models.CharField(default='08:00', help_text=b'Race start time information', max_length=100),
            preserve_default=False,
        ),
    ]
