# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0019_auto_20160413_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='commissaire',
            field=models.CharField(default=b'', max_length=10, verbose_name=b'Commissaire Level'),
        ),
        migrations.AddField(
            model_name='rider',
            name='commissaire_valid',
            field=models.DateField(blank=True, null=True, verbose_name=b'Commissaire Valid To'),
        ),
    ]
