# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0020_auto_20160423_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='phone',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'Phone'),
        ),
    ]
