# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0023_auto_20160430_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='race',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rider',
            name='commissaire',
            field=models.CharField(default=b'0', max_length=10, verbose_name=b'Commissaire Level'),
        ),
        migrations.AddField(
            model_name='racestaff',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.Race'),
        ),
        migrations.AddField(
            model_name='racestaff',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.Rider'),
        ),
        migrations.AddField(
            model_name='racestaff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.ClubRole'),
        ),
    ]
