# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0025_auto_20160719_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='manage_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='manage_results',
            field=models.BooleanField(default=False),
        ),
    ]
