# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0026_auto_20160730_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='manage_races',
            field=models.BooleanField(default=False),
        ),
    ]
