# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0027_club_manage_races'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='commissaire',
            field=models.CharField(default=b'0', help_text=b'0 if not a Commissaire, otherwise eg. 1, RT', max_length=10, verbose_name=b'Commissaire Level'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='official',
            field=models.BooleanField(default=False, help_text=b'Officials can view and edit member details, schedule races, upload results', verbose_name=b'Club Official'),
        ),
    ]
