version: '3.7'

services:
  web:
    build: .
    command: gunicorn -c ./gunicorn.config.py races.wsgi
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on: 
      - db
  db:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=cabici
        - POSTGRES_PASSWORD=cabici
        - POSTGRES_DB=cabici_dev

volumes:
  postgres_data:
