# sample data for testing IMG file import
# data format is same as the result of parse_img_members
import datetime
rows = [
 {u'Email Address': u'valverde@worldtour.com',
  u'Member Number': u'ESP19800425',
  u'AUDAX Number': u'0',
  u'Add Date': datetime.date(2010, 3, 6),
  u'Address1': u'368B Some St.',
  u'Address2': None,
  u'Allergies or medical conditions (please list)': None,
  u'Are you a para-cyclist?': u'No',
  u'Business': u' ',
  u'Coach Accreditation Expiry Date': None,
  u'Coach Level': None,
  u'Commissaire Accreditation Expiry Date': None,
  u'Commissaire Level (e.g. 2 Road Track MTB)': u'0',
  u'Company Name': None,
  u'Country': u'Australia',
  u'DOB': datetime.date(1971, 1, 3),
  u'Deceased': u'No',
  u'Direct': u' ',
  u'Directory': u'Yes',
  u'Edit Date': datetime.date(2014, 1, 1),
  u'Education': None,
  u'Emergency Contact Number': u'0408607999',
  u'Emergency Contact Person': u'Mary Valverde',
  u'Exclude from RTP': None,
  u'Facsimile': u' ',
  u'Financial Date': datetime.date(datetime.date.today().year, 12, 31),
  u'First Aid certificate expiry date': None,
  u'First Name': u'Alejandro',
  u'Gender': u'Male',
  u'Initial': None,
  u'International Licence Code': None,
  u'Last Name': u'VALVERDE BELMONTE',
  u'Mailing List': u'Yes',
  u'Marital Status': None,
  u'Member Types': u'RACING Membership',
  u'Mobile': u' 0415 999999',
  u'NCAS Accreditation Number': u'0',
  u'NSW Road Handicap Data': 'A1',
  u'NSW Track Handicap Data': None,
  u'Occupation': None,
  u'Other Names': u'G',
  u'Para Cycling Classification (if applicable)': None,
  u'Password': u'sdkflsdkfj',
  u'Please indicate your preferred discipline': None,
  u'Postcode': u'2203',
  u'Primary': u'0',
  u'Private': u' ',
  u'State': u'NSW',
  u'Status': u'Active',
  u'Subscriptions': u'Race Masters 3',
  u'Suburb': u'DULWICH HILL',
  u'Title': u'Mr',
  u'Traffic Management Qualification': None,
  u'Traffic Management Qualification Expiration Date': None,
  u'UserName': u'sldkfjldfkj',
  u'Working with Children clearance expiry date': None},
 {u'Email Address': u'valverde@worldtour.com',
  u'Member Number': u'ESP198004999',
  u'AUDAX Number': u'0',
  u'Add Date': datetime.date(2010, 3, 6),
  u'Address1': u'368B Some St.',
  u'Address2': None,
  u'Allergies or medical conditions (please list)': None,
  u'Are you a para-cyclist?': u'No',
  u'Business': u' ',
  u'Coach Accreditation Expiry Date': None,
  u'Coach Level': None,
  u'Commissaire Accreditation Expiry Date': None,
  u'Commissaire Level (e.g. 2 Road Track MTB)': u'0',
  u'Company Name': None,
  u'Country': u'Australia',
  u'DOB': datetime.date(1971, 1, 3),
  u'Deceased': u'No',
  u'Direct': u' ',
  u'Directory': u'Yes',
  u'Edit Date': datetime.date(2014, 1, 1),
  u'Education': None,
  u'Emergency Contact Number': u'0408607999',
  u'Emergency Contact Person': u'Mary Valverde',
  u'Exclude from RTP': None,
  u'Facsimile': u' ',
  u'Financial Date': datetime.date(datetime.date.today().year-1, 12, 31),
  u'First Aid certificate expiry date': None,
  u'First Name': u'Alejandro',
  u'Gender': u'Male',
  u'Initial': None,
  u'International Licence Code': None,
  u'Last Name': u'VALVERDE BELMONTE',
  u'Mailing List': u'Yes',
  u'Marital Status': None,
  u'Member Types': u'RACING Membership',
  u'Mobile': u' 0415 999999',
  u'NCAS Accreditation Number': u'0',
  u'NSW Road Handicap Data': None,
  u'NSW Track Handicap Data': None,
  u'Occupation': None,
  u'Other Names': u'G',
  u'Para Cycling Classification (if applicable)': None,
  u'Password': u'sdkflsdkfj',
  u'Please indicate your preferred discipline': None,
  u'Postcode': u'2203',
  u'Primary': u'0',
  u'Private': u' ',
  u'State': u'NSW',
  u'Status': u'Active',
  u'Subscriptions': u'Race Masters 3',
  u'Suburb': u'DULWICH HILL',
  u'Title': u'Mr',
  u'Traffic Management Qualification': None,
  u'Traffic Management Qualification Expiration Date': None,
  u'UserName': u'sldkfjldfkj',
  u'Working with Children clearance expiry date': None},
 {u'Email Address': u'stephen@example.com',
  u'Member Number': u'160888',
  u'AUDAX Number': u'0',
  u'Add Date': datetime.date(2009, 10, 21),
  u'Address1': u'43 Somewhere Ave',
  u'Address2': None,
  u'Allergies or medical conditions (please list)': u'nil',
  u'Are you a para-cyclist?': u'No',
  u'Business': u' ',
  u'Coach Accreditation Expiry Date': None,
  u'Coach Level': None,
  u'Commissaire Accreditation Expiry Date': None,
  u'Commissaire Level (e.g. 2 Road Track MTB)': u'0',
  u'Company Name': None,
  u'Country': u'Australia',
  u'DOB': datetime.date(1956, 3, 11),
  u'Deceased': u'No',
  u'Direct': u' ',
  u'Directory': u'No',
  u'Edit Date': datetime.date(2015, 12, 21),
  u'Education': None,
  u'Emergency Contact Number': u'0415136999',
  u'Emergency Contact Person': u'Michele MyBelle',
  u'Exclude from RTP': None,
  u'Facsimile': u' ',
  u'Financial Date': datetime.date(2016, 12, 31),
  u'First Aid certificate expiry date': None,
  u'First Name': u'Stephen',
  u'Gender': u'Male',
  u'Initial': None,
  u'International Licence Code': None,
  u'Last Name': u'SMITH',
  u'Mailing List': u'Yes',
  u'Marital Status': None,
  u'Member Types': u'RIDE Membership',
  u'Mobile': u' 0424 836 999',
  u'NCAS Accreditation Number': u'0',
  u'NSW Road Handicap Data': u'E3',
  u'NSW Track Handicap Data': None,
  u'Occupation': u'accountant',
  u'Other Names': None,
  u'Para Cycling Classification (if applicable)': None,
  u'Password': u'160888',
  u'Please indicate your preferred discipline': u'Road',
  u'Postcode': u'2073',
  u'Primary': u'0',
  u'Private': u'02 9498 9999',
  u'State': u'NSW',
  u'Status': u'Active',
  u'Subscriptions': u'Ride - Adult (19 - 64)',
  u'Suburb': u'WEST PYMBLE',
  u'Title': u'Mr',
  u'Traffic Management Qualification': None,
  u'Traffic Management Qualification Expiration Date': None,
  u'UserName': u'STEPHEN SMITH',
  u'Working with Children clearance expiry date': None},
 {u'Email Address': u'anotherrider@worldtour.com',
  u'Member Number': u'ANO1980044459',
  u'AUDAX Number': u'0',
  u'Add Date': datetime.date(2010, 3, 6),
  u'Address1': u'368B Some St.',
  u'Address2': None,
  u'Allergies or medical conditions (please list)': None,
  u'Are you a para-cyclist?': u'No',
  u'Business': u' ',
  u'Coach Accreditation Expiry Date': None,
  u'Coach Level': None,
  u'Commissaire Accreditation Expiry Date': datetime.date(datetime.date.today().year+1, 12, 31),
  u'Commissaire Level (e.g. 2 Road Track MTB)': u'1 R,T',
  u'Company Name': None,
  u'Country': u'Australia',
  u'DOB': datetime.date(1971, 1, 3),
  u'Deceased': u'No',
  u'Direct': u' ',
  u'Directory': u'Yes',
  u'Edit Date': datetime.date(2014, 1, 1),
  u'Education': None,
  u'Emergency Contact Number': u'0408607999',
  u'Emergency Contact Person': u'Mary Valverde',
  u'Exclude from RTP': None,
  u'Facsimile': u' ',
  u'Financial Date': datetime.date(datetime.date.today().year, 12, 31),
  u'First Aid certificate expiry date': None,
  u'First Name': u'Alejandro',
  u'Gender': u'Male',
  u'Initial': None,
  u'International Licence Code': None,
  u'Last Name': u'SOMEONE ELSE',
  u'Mailing List': u'Yes',
  u'Marital Status': None,
  u'Member Types': u'RACING Membership',
  u'Mobile': u' 0415 999999',
  u'NCAS Accreditation Number': u'0',
  u'NSW Road Handicap Data': "E3",
  u'NSW Track Handicap Data': None,
  u'Occupation': None,
  u'Other Names': u'G',
  u'Para Cycling Classification (if applicable)': None,
  u'Password': u'sdkflsdkfj',
  u'Please indicate your preferred discipline': None,
  u'Postcode': u'2203',
  u'Primary': u'0',
  u'Private': u' ',
  u'State': u'NSW',
  u'Status': u'Active',
  u'Subscriptions': u'Race Masters 3',
  u'Suburb': u'DULWICH HILL',
  u'Title': u'Mr',
  u'Traffic Management Qualification': None,
  u'Traffic Management Qualification Expiration Date': None,
  u'UserName': u'sldkfjldfkj',
  u'Working with Children clearance expiry date': None},
 {u'Email Address': u'anotherrider@worldtour.com',
  u'Member Number': u'ANO1980044459',
  u'AUDAX Number': u'0',
  u'Add Date': datetime.date(2010, 3, 6),
  u'Address1': u'368B Some St.',
  u'Address2': None,
  u'Allergies or medical conditions (please list)': None,
  u'Are you a para-cyclist?': u'No',
  u'Business': u' ',
  u'Coach Accreditation Expiry Date': None,
  u'Coach Level': None,
  u'Commissaire Accreditation Expiry Date': datetime.date(datetime.date.today().year+1, 12, 31),
  u'Commissaire Level (e.g. 2 Road Track MTB)': u'1 R,T',
  u'Company Name': None,
  u'Country': u'Australia',
  u'DOB': datetime.date(1971, 1, 3),
  u'Deceased': u'No',
  u'Direct': u' ',
  u'Directory': u'Yes',
  u'Edit Date': datetime.date(2014, 1, 1),
  u'Education': None,
  u'Emergency Contact Number': u'0408607999',
  u'Emergency Contact Person': u'Mary Valverde',
  u'Exclude from RTP': None,
  u'Facsimile': u' ',
  u'Financial Date': datetime.date(datetime.date.today().year-1, 12, 31),
  u'First Aid certificate expiry date': None,
  u'First Name': u'Alejandro',
  u'Gender': u'Male',
  u'Initial': None,
  u'International Licence Code': None,
  u'Last Name': u'SOMEONE ELSE',
  u'Mailing List': u'Yes',
  u'Marital Status': None,
  u'Member Types': u'RACING Membership',
  u'Mobile': u' 0415 999999',
  u'NCAS Accreditation Number': u'0',
  u'NSW Road Handicap Data': None,
  u'NSW Track Handicap Data': None,
  u'Occupation': None,
  u'Other Names': u'G',
  u'Para Cycling Classification (if applicable)': None,
  u'Password': u'sdkflsdkfj',
  u'Please indicate your preferred discipline': None,
  u'Postcode': u'2203',
  u'Primary': u'0',
  u'Private': u' ',
  u'State': u'NSW',
  u'Status': u'Active',
  u'Subscriptions': u'Race Masters 3',
  u'Suburb': u'DULWICH HILL',
  u'Title': u'Mr',
  u'Traffic Management Qualification': None,
  u'Traffic Management Qualification Expiration Date': None,
  u'UserName': u'sldkfjldfkj',
  u'Working with Children clearance expiry date': None},
 {u'Email Address': u'nodob@example.com',
  u'Member Number': u'1234567',
  u'AUDAX Number': u'0',
  u'Add Date': datetime.date(2010, 3, 6),
  u'Address1': u'368B Some St.',
  u'Address2': None,
  u'Allergies or medical conditions (please list)': None,
  u'Are you a para-cyclist?': u'No',
  u'Business': u' ',
  u'Coach Accreditation Expiry Date': None,
  u'Coach Level': None,
  u'Commissaire Accreditation Expiry Date': None,
  u'Commissaire Level (e.g. 2 Road Track MTB)': u'0',
  u'Company Name': None,
  u'Country': u'Australia',
  u'DOB': datetime.date(1975, 6, 7),
  u'Deceased': u'No',
  u'Direct': u' ',
  u'Directory': u'Yes',
  u'Edit Date': datetime.date(2014, 1, 1),
  u'Education': None,
  u'Emergency Contact Number': u'0408607999',
  u'Emergency Contact Person': u'Mary Valverde',
  u'Exclude from RTP': None,
  u'Facsimile': u' ',
  u'Financial Date': datetime.date(datetime.date.today().year-1, 12, 31),
  u'First Aid certificate expiry date': None,
  u'First Name': u'Alejandro',
  u'Gender': u'Male',
  u'Initial': None,
  u'International Licence Code': None,
  u'Last Name': u'SOMEONE ELSE',
  u'Mailing List': u'Yes',
  u'Marital Status': None,
  u'Member Types': u'RACING Membership',
  u'Mobile': u' 0415 999999',
  u'NCAS Accreditation Number': u'0',
  u'NSW Road Handicap Data': None,
  u'NSW Track Handicap Data': None,
  u'Occupation': None,
  u'Other Names': u'G',
  u'Para Cycling Classification (if applicable)': None,
  u'Password': u'sdkflsdkfj',
  u'Please indicate your preferred discipline': None,
  u'Postcode': u'2203',
  u'Primary': u'0',
  u'Private': u' ',
  u'State': u'NSW',
  u'Status': u'Active',
  u'Subscriptions': u'Race Masters 3',
  u'Suburb': u'DULWICH HILL',
  u'Title': u'Mr',
  u'Traffic Management Qualification': None,
  u'Traffic Management Qualification Expiration Date': None,
  u'UserName': u'sldkfjldfkj',
  u'Working with Children clearance expiry date': None},
 ]
