#!/usr/bin/python
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# sample data for testing IMG file import
# data format is same as the result of parse_img_members
import datetime
rows = [
 {'Email Address': 'valverde@worldtour.com',
  'Member Number': 'ESP19800425',
  'AUDAX Number': '0',
  'Add Date': datetime.date(2010, 3, 6),
  'Address1': '368B Some St.',
  'Address2': None,
  'Allergies or medical conditions (please list)': None,
  'Are you a para-cyclist?': 'No',
  'Business': ' ',
  'Coach Accreditation Expiry Date': None,
  'Coach Level': None,
  'Commissaire Accreditation Expiry Date': None,
  'Commissaire Level (e.g. 2 Road Track MTB)': '0',
  'Company Name': None,
  'Country': 'Australia',
  'DOB': datetime.date(1971, 1, 3),
  'Deceased': 'No',
  'Direct': ' ',
  'Directory': 'Yes',
  'Edit Date': datetime.date(2014, 1, 1),
  'Education': None,
  'Emergency Contact Number': '0408607999',
  'Emergency Contact Person': 'Mary Valverde',
  'Exclude from RTP': None,
  'Facsimile': ' ',
  'Financial Date': datetime.date(datetime.date.today().year, 12, 31),
  'First Aid certificate expiry date': None,
  'First Name': 'Alejandro',
  'Gender': 'Male',
  'Initial': None,
  'International Licence Code': None,
  'Last Name': 'VALVERDE BELMONTE',
  'Mailing List': 'Yes',
  'Marital Status': None,
  'Member Types': 'RACING Membership',
  'Mobile': ' 0415 999999',
  'NCAS Accreditation Number': '0',
  'NSW Road Handicap Data': 'A1',
  'NSW Track Handicap Data': None,
  'Occupation': None,
  'Other Names': 'G',
  'Para Cycling Classification (if applicable)': None,
  'Password': 'sdkflsdkfj',
  'Please indicate your preferred discipline': None,
  'Postcode': '2203',
  'Primary': '0',
  'Private': ' ',
  'State': 'NSW',
  'Status': 'Active',
  'Subscriptions': 'Race Masters 3',
  'Suburb': 'DULWICH HILL',
  'Title': 'Mr',
  'Traffic Management Qualification': None,
  'Traffic Management Qualification Expiration Date': None,
  'UserName': 'sldkfjldfkj',
  'Working with Children clearance expiry date': None},
 {'Email Address': 'valverde@worldtour.com',
  'Member Number': 'ESP198004999',
  'AUDAX Number': '0',
  'Add Date': datetime.date(2010, 3, 6),
  'Address1': '368B Some St.',
  'Address2': None,
  'Allergies or medical conditions (please list)': None,
  'Are you a para-cyclist?': 'No',
  'Business': ' ',
  'Coach Accreditation Expiry Date': None,
  'Coach Level': None,
  'Commissaire Accreditation Expiry Date': None,
  'Commissaire Level (e.g. 2 Road Track MTB)': '0',
  'Company Name': None,
  'Country': 'Australia',
  'DOB': datetime.date(1971, 1, 3),
  'Deceased': 'No',
  'Direct': ' ',
  'Directory': 'Yes',
  'Edit Date': datetime.date(2014, 1, 1),
  'Education': None,
  'Emergency Contact Number': '0408607999',
  'Emergency Contact Person': 'Mary Valverde',
  'Exclude from RTP': None,
  'Facsimile': ' ',
  'Financial Date': datetime.date(datetime.date.today().year-1, 12, 31),
  'First Aid certificate expiry date': None,
  'First Name': 'Alejandro',
  'Gender': 'Male',
  'Initial': None,
  'International Licence Code': None,
  'Last Name': 'VALVERDE BELMONTE',
  'Mailing List': 'Yes',
  'Marital Status': None,
  'Member Types': 'RACING Membership',
  'Mobile': ' 0415 999999',
  'NCAS Accreditation Number': '0',
  'NSW Road Handicap Data': None,
  'NSW Track Handicap Data': None,
  'Occupation': None,
  'Other Names': 'G',
  'Para Cycling Classification (if applicable)': None,
  'Password': 'sdkflsdkfj',
  'Please indicate your preferred discipline': None,
  'Postcode': '2203',
  'Primary': '0',
  'Private': ' ',
  'State': 'NSW',
  'Status': 'Active',
  'Subscriptions': 'Race Masters 3',
  'Suburb': 'DULWICH HILL',
  'Title': 'Mr',
  'Traffic Management Qualification': None,
  'Traffic Management Qualification Expiration Date': None,
  'UserName': 'sldkfjldfkj',
  'Working with Children clearance expiry date': None},
 {'Email Address': 'stephen@example.com',
  'Member Number': '160888',
  'AUDAX Number': '0',
  'Add Date': datetime.date(2009, 10, 21),
  'Address1': '43 Somewhere Ave',
  'Address2': None,
  'Allergies or medical conditions (please list)': 'nil',
  'Are you a para-cyclist?': 'No',
  'Business': ' ',
  'Coach Accreditation Expiry Date': None,
  'Coach Level': None,
  'Commissaire Accreditation Expiry Date': None,
  'Commissaire Level (e.g. 2 Road Track MTB)': '0',
  'Company Name': None,
  'Country': 'Australia',
  'DOB': datetime.date(1956, 3, 11),
  'Deceased': 'No',
  'Direct': ' ',
  'Directory': 'No',
  'Edit Date': datetime.date(2015, 12, 21),
  'Education': None,
  'Emergency Contact Number': '0415136999',
  'Emergency Contact Person': 'Michele MyBelle',
  'Exclude from RTP': None,
  'Facsimile': ' ',
  'Financial Date': datetime.date(datetime.date.today().year, 12, 31),
  'First Aid certificate expiry date': None,
  'First Name': 'Stephen',
  'Gender': 'Male',
  'Initial': None,
  'International Licence Code': None,
  'Last Name': 'SMITH',
  'Mailing List': 'Yes',
  'Marital Status': None,
  'Member Types': 'RIDE Membership',
  'Mobile': ' 0424 836 999',
  'NCAS Accreditation Number': '0',
  'NSW Road Handicap Data': 'E3',
  'NSW Track Handicap Data': None,
  'Occupation': 'accountant',
  'Other Names': None,
  'Para Cycling Classification (if applicable)': None,
  'Password': '160888',
  'Please indicate your preferred discipline': 'Road',
  'Postcode': '2073',
  'Primary': '0',
  'Private': '02 9498 9999',
  'State': 'NSW',
  'Status': 'Active',
  'Subscriptions': 'Ride - Adult (19 - 64)',
  'Suburb': 'WEST PYMBLE',
  'Title': 'Mr',
  'Traffic Management Qualification': None,
  'Traffic Management Qualification Expiration Date': None,
  'UserName': 'STEPHEN SMITH',
  'Working with Children clearance expiry date': None},
 {'Email Address': 'anotherrider@worldtour.com',
  'Member Number': 'ANO1980044459',
  'AUDAX Number': '0',
  'Add Date': datetime.date(2010, 3, 6),
  'Address1': '368B Some St.',
  'Address2': None,
  'Allergies or medical conditions (please list)': None,
  'Are you a para-cyclist?': 'No',
  'Business': ' ',
  'Coach Accreditation Expiry Date': None,
  'Coach Level': None,
  'Commissaire Accreditation Expiry Date': datetime.date(datetime.date.today().year+1, 12, 31),
  'Commissaire Level (e.g. 2 Road Track MTB)': '1 R,T',
  'Company Name': None,
  'Country': 'Australia',
  'DOB': datetime.date(1971, 1, 3),
  'Deceased': 'No',
  'Direct': ' ',
  'Directory': 'Yes',
  'Edit Date': datetime.date(2014, 1, 1),
  'Education': None,
  'Emergency Contact Number': '0408607999',
  'Emergency Contact Person': 'Mary Valverde',
  'Exclude from RTP': None,
  'Facsimile': ' ',
  'Financial Date': datetime.date(datetime.date.today().year, 12, 31),
  'First Aid certificate expiry date': None,
  'First Name': 'Alejandro',
  'Gender': 'Male',
  'Initial': None,
  'International Licence Code': None,
  'Last Name': 'SOMEONE ELSE',
  'Mailing List': 'Yes',
  'Marital Status': None,
  'Member Types': 'RACING Membership',
  'Mobile': ' 0415 999999',
  'NCAS Accreditation Number': '0',
  'NSW Road Handicap Data': "E3",
  'NSW Track Handicap Data': None,
  'Occupation': None,
  'Other Names': 'G',
  'Para Cycling Classification (if applicable)': None,
  'Password': 'sdkflsdkfj',
  'Please indicate your preferred discipline': None,
  'Postcode': '2203',
  'Primary': '0',
  'Private': ' ',
  'State': 'NSW',
  'Status': 'Active',
  'Subscriptions': 'Race Masters 3',
  'Suburb': 'DULWICH HILL',
  'Title': 'Mr',
  'Traffic Management Qualification': None,
  'Traffic Management Qualification Expiration Date': None,
  'UserName': 'sldkfjldfkj',
  'Working with Children clearance expiry date': None},
 {'Email Address': 'anotherrider@worldtour.com',
  'Member Number': 'ANO1980044459',
  'AUDAX Number': '0',
  'Add Date': datetime.date(2010, 3, 6),
  'Address1': '368B Some St.',
  'Address2': None,
  'Allergies or medical conditions (please list)': None,
  'Are you a para-cyclist?': 'No',
  'Business': ' ',
  'Coach Accreditation Expiry Date': None,
  'Coach Level': None,
  'Commissaire Accreditation Expiry Date': datetime.date(datetime.date.today().year+1, 12, 31),
  'Commissaire Level (e.g. 2 Road Track MTB)': '1 R,T',
  'Company Name': None,
  'Country': 'Australia',
  'DOB': datetime.date(1971, 1, 3),
  'Deceased': 'No',
  'Direct': ' ',
  'Directory': 'Yes',
  'Edit Date': datetime.date(2014, 1, 1),
  'Education': None,
  'Emergency Contact Number': '0408607999',
  'Emergency Contact Person': 'Mary Valverde',
  'Exclude from RTP': None,
  'Facsimile': ' ',
  'Financial Date': datetime.date(datetime.date.today().year-1, 12, 31),
  'First Aid certificate expiry date': None,
  'First Name': 'Alejandro',
  'Gender': 'Male',
  'Initial': None,
  'International Licence Code': None,
  'Last Name': 'SOMEONE ELSE',
  'Mailing List': 'Yes',
  'Marital Status': None,
  'Member Types': 'RACING Membership',
  'Mobile': ' 0415 999999',
  'NCAS Accreditation Number': '0',
  'NSW Road Handicap Data': None,
  'NSW Track Handicap Data': None,
  'Occupation': None,
  'Other Names': 'G',
  'Para Cycling Classification (if applicable)': None,
  'Password': 'sdkflsdkfj',
  'Please indicate your preferred discipline': None,
  'Postcode': '2203',
  'Primary': '0',
  'Private': ' ',
  'State': 'NSW',
  'Status': 'Active',
  'Subscriptions': 'Race Masters 3',
  'Suburb': 'DULWICH HILL',
  'Title': 'Mr',
  'Traffic Management Qualification': None,
  'Traffic Management Qualification Expiration Date': None,
  'UserName': 'sldkfjldfkj',
  'Working with Children clearance expiry date': None},
 {'Email Address': 'nodob@example.com',
  'Member Number': '1234567',
  'AUDAX Number': '0',
  'Add Date': datetime.date(2010, 3, 6),
  'Address1': '368B Some St.',
  'Address2': None,
  'Allergies or medical conditions (please list)': None,
  'Are you a para-cyclist?': 'No',
  'Business': ' ',
  'Coach Accreditation Expiry Date': None,
  'Coach Level': None,
  'Commissaire Accreditation Expiry Date': None,
  'Commissaire Level (e.g. 2 Road Track MTB)': '0',
  'Company Name': None,
  'Country': 'Australia',
  'DOB': datetime.date(1975, 6, 7),
  'Deceased': 'No',
  'Direct': ' ',
  'Directory': 'Yes',
  'Edit Date': datetime.date(2014, 1, 1),
  'Education': None,
  'Emergency Contact Number': '0408607999',
  'Emergency Contact Person': 'Mary Valverde',
  'Exclude from RTP': None,
  'Facsimile': ' ',
  'Financial Date': datetime.date(datetime.date.today().year, 12, 31),
  'First Aid certificate expiry date': None,
  'First Name': 'Alejandro',
  'Gender': 'Female',
  'Initial': None,
  'International Licence Code': None,
  'Last Name': 'SOMEONE ELSE',
  'Mailing List': 'Yes',
  'Marital Status': None,
  'Member Types': 'RACING Membership',
  'Mobile': ' 0415 999999',
  'NCAS Accreditation Number': '0',
  'NSW Road Handicap Data': None,
  'NSW Track Handicap Data': None,
  'Occupation': None,
  'Other Names': 'G',
  'Para Cycling Classification (if applicable)': None,
  'Password': 'sdkflsdkfj',
  'Please indicate your preferred discipline': None,
  'Postcode': '2203',
  'Primary': '0',
  'Private': ' ',
  'State': 'NSW',
  'Status': 'Active',
  'Subscriptions': 'Race Masters 3',
  'Suburb': 'DULWICH HILL',
  'Title': 'Mr',
  'Traffic Management Qualification': None,
  'Traffic Management Qualification Expiration Date': None,
  'UserName': 'sldkfjldfkj',
  'Working with Children clearance expiry date': None},
 ]
