# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0002_auto_20160908_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointscoretally',
            options={'ordering': ['-points', 'eventcount']},
        ),
        migrations.AddField(
            model_name='race',
            name='category',
            field=models.CharField(choices=[(b'1', b'Category 1 Open and State Championships'), (b'2', b'Category 2 Open/Masters Open/Junior Open'), (b'3', b'Category 3 Club/Inter-Club'), (b'Junior', b'Junior Club'), (b'Rec', b'Recreational/Timed Rides')], default=b'3', max_length=10),
        ),
        migrations.AddField(
            model_name='race',
            name='discipline',
            field=models.CharField(choices=[(b'r', b'Road'), (b't', b'Track'), (b'cx', b'Cyclocross'), (b'mtb', b'MTB'), (b'bmx', b'BMX')], default=b'r', max_length=10),
        ),
        migrations.AddField(
            model_name='race',
            name='licencereq',
            field=models.CharField(choices=[(b'e.m', b'Elite Men'), (b'e.w', b'Elite Women'), (b'e.mw', b'Elite Men & Women'), (b'm.mw', b'Masters Men & Women'), (b'm.m', b'Masters Men'), (b'm.w', b'Masters Women'), (b'em.mw', b'Elite or Masters Men & Women'), (b'em.m', b'Elite or Masters Men'), (b'em.w', b'Elite or Masters Women'), (b'j.mw', b'Junior'), (b'k.mw', b'Kids'), (b'p.mw', b'Para-cyclist Men & Women'), (b'p.m', b'Para-cyclist Men'), (b'p.w', b'Para-cyclist Women')], default=b'em.mw', max_length=10),
        ),
        migrations.AlterField(
            model_name='pointscoretally',
            name='pointscore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='cabici.PointScore'),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published'), (b'w', b'Withdrawn'), (b'c', b'Cancelled')], default=b'p', help_text=b' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='rider',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=2, verbose_name=b'Gender'),
        ),
    ]
