# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 01:26


from django.db import migrations, models

def forwards(apps, schema_editor):
    """Set the shortname based on the truncated name field"""

    racecourse_model = apps.get_model('cabici', 'racecourse')
    for rc in racecourse_model.objects.all():
        rc.shortname = rc.name[:20]
        rc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0003_auto_20161127_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racecourse',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='racecourse',
            name='shortname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
