#!/usr/bin/python
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 01:26


from django.db import migrations, models

def forwards(apps, schema_editor):
    """Set the shortname based on the truncated name field"""

    racecourse_model = apps.get_model('cabici', 'racecourse')
    for rc in racecourse_model.objects.all():
        rc.shortname = rc.name[:20]
        rc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0003_auto_20161127_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racecourse',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='racecourse',
            name='shortname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
