# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-04 10:45


from django.db import migrations, models


def forwards(apps, schema_editor):
    """Set the usual_grade field based on grade"""

    raceresult_model = apps.get_model('cabici', 'raceresult')
    for rc in raceresult_model.objects.all():
        rc.usual_grade = rc.grade
        rc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0005_auto_20170101_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='usual_grade',
            field=models.CharField(default='A', max_length=10, verbose_name=b'Usual Grade'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),

    ]
