# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-05 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0006_raceresult_usual_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointscoretally',
            name='audit',
            field=models.TextField(default=b'[]'),
        ),
    ]
