# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import datetime

def copy_year_to_date(apps, schema_editor):
    """Add a date field for each membership based on existing year field"""

    Membership = apps.get_model('cabici', 'Membership')
    for membership in Membership.objects.all():
        membership.date = datetime.date(day=31, month=12, year=membership.year)
        membership.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0007_pointscoretally_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(copy_year_to_date),
    ]
