#!/usr/bin/python
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-09 11:31


from django.db import migrations, models
import datetime

def copy_year_to_date(apps, schema_editor):
    """Add a date field for each membership based on existing year field"""

    Membership = apps.get_model('cabici', 'Membership')
    for membership in Membership.objects.all():
        membership.date = datetime.date(day=31, month=12, year=membership.year)
        membership.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0007_pointscoretally_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(copy_year_to_date),
    ]
