#!/usr/bin/python
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.1 on 2018-12-26 11:27

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0010_auto_20171230_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='race',
            name='grading',
            field=models.CharField(default='A,B,C,D,E,F', max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='icalpatterns',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='icalurl',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='clubgrade',
            name='grade',
            field=models.CharField(max_length=10, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='clubrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='category',
            field=models.CharField(choices=[('Ride', 'ride'), ('Race', 'race'), ('Non-riding', 'non-riding')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pointscore',
            name='participation',
            field=models.IntegerField(default=2, verbose_name='Points for participation'),
        ),
        migrations.AlterField(
            model_name='pointscore',
            name='points',
            field=models.CharField(default='7,6,5,4,3', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Points for larger races'),
        ),
        migrations.AlterField(
            model_name='pointscore',
            name='smallpoints',
            field=models.CharField(default='5,4', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Points for small races'),
        ),
        migrations.AlterField(
            model_name='pointscore',
            name='smallthreshold',
            field=models.IntegerField(default=12, verbose_name='Small Race Threshold'),
        ),
        migrations.AlterField(
            model_name='pointscoretally',
            name='audit',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='race',
            name='category',
            field=models.CharField(choices=[('1', 'Category 1 Open and State Championships'), ('2', 'Category 2 Open/Masters Open/Junior Open'), ('3', 'Category 3 Club/Inter-Club'), ('Junior', 'Junior Club'), ('Rec', 'Recreational/Timed Rides')], default='3', max_length=10),
        ),
        migrations.AlterField(
            model_name='race',
            name='club',
            field=models.ForeignKey(help_text=' ', on_delete=django.db.models.deletion.CASCADE, related_name='races', to='cabici.Club'),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(help_text=' '),
        ),
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, default='', help_text=' '),
        ),
        migrations.AlterField(
            model_name='race',
            name='discipline',
            field=models.CharField(choices=[('r', 'Road'), ('t', 'Track'), ('cx', 'Cyclocross'), ('mtb', 'MTB'), ('bmx', 'BMX')], default='r', max_length=10),
        ),
        migrations.AlterField(
            model_name='race',
            name='licencereq',
            field=models.CharField(choices=[('e.m', 'Elite Men'), ('e.w', 'Elite Women'), ('e.mw', 'Elite Men & Women'), ('m.mw', 'Masters Men & Women'), ('m.m', 'Masters Men'), ('m.w', 'Masters Women'), ('em.mw', 'Elite or Masters Men & Women'), ('em.m', 'Elite or Masters Men'), ('em.w', 'Elite or Masters Women'), ('j.mw', 'Junior'), ('k.mw', 'Kids'), ('p.mw', 'Para-cyclist Men & Women'), ('p.m', 'Para-cyclist Men'), ('p.w', 'Para-cyclist Women')], default='em.mw', max_length=10),
        ),
        migrations.AlterField(
            model_name='race',
            name='location',
            field=models.ForeignKey(help_text=' ', on_delete=django.db.models.deletion.CASCADE, to='cabici.RaceCourse'),
        ),
        migrations.AlterField(
            model_name='race',
            name='signontime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='starttime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn'), ('c', 'Cancelled')], default='p', help_text=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='race',
            name='website',
            field=models.URLField(blank=True, help_text=' ', max_length=400),
        ),
        migrations.AlterField(
            model_name='racecourse',
            name='shortname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='dnf',
            field=models.BooleanField(default=False, verbose_name='DNF'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='grade',
            field=models.CharField(max_length=10, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bib Number'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='place',
            field=models.IntegerField(blank=True, help_text='Enter finishing position (eg. 1-5), leave blank for a result out of the placings.', null=True, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='usual_grade',
            field=models.CharField(max_length=10, verbose_name='Usual Grade'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='commissaire',
            field=models.CharField(blank=True, default='0', help_text='0 if not a Commissaire, otherwise eg. 1, RT', max_length=10, verbose_name='Commissaire Level'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='commissaire_valid',
            field=models.DateField(blank=True, null=True, verbose_name='Commissaire Valid To'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(1970, 1, 1), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='emergencyname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='emergencyphone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='emergencyrelationship',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Emergency Contact Relationship'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='licenceno',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Licence Number'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='official',
            field=models.BooleanField(default=False, help_text='Officials can view and edit member details, schedule races, upload results', verbose_name='Club Official'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='state',
            field=models.CharField(blank=True, choices=[('ACT', 'Australian Capital Territory'), ('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], default='NSW', max_length=10, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='streetaddress',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='suburb',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Suburb'),
        ),
    ]
