# Generated by Django 2.1 on 2019-01-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0011_auto_20181226_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['date', 'category']},
        ),
    ]
