#!/usr/bin/python
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.1 on 2019-05-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0012_auto_20190112_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointscore',
            name='method',
            field=models.CharField(choices=[('WMCC', 'WMCC'), ('LACC', 'LACC')], default='WMCC', max_length=10, verbose_name='Pointscore Method'),
        ),
    ]
