# Generated by Django 2.1 on 2019-10-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabici', '0013_pointscore_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
