#!/usr/bin/python
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.2 on 2022-11-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabici", "0014_rider_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="add_on",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="race",
            name="grading",
            field=models.CharField(default="A,A2,B,C,D,E,F", max_length=50),
        ),
        migrations.AlterField(
            model_name="rider",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=2,
                verbose_name="Gender",
            ),
        ),
    ]
