# Generated by Django 4.1.2 on 2022-11-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabici", "0014_rider_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="add_on",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="race",
            name="grading",
            field=models.CharField(default="A,A2,B,C,D,E,F", max_length=50),
        ),
        migrations.AlterField(
            model_name="rider",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=2,
                verbose_name="Gender",
            ),
        ),
    ]
