# Generated by Django 4.2.23 on 2025-11-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cabici", "0015_membership_add_on_alter_race_grading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="auscycling_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AusCycling API OAuth2 Client ID",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="auscycling_client_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AusCycling API OAuth2 Client Secret",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="auscycling_club_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AusCycling Club ID for membership verification",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="last_validated",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time membership was validated with AusCycling API",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="validation_error",
            field=models.TextField(
                blank=True, default="", help_text="Last validation error message if any"
            ),
        ),
    ]
