name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t waratahmasters.races:latest
    - name: Login to package repository
      run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: push new docker image
      run: docker push waratahmasters.races:latest
      